import Head from 'next/head';
import './globals.css'; // Adjust the path to match your project structure

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Welcome to My Next.js App!</h1>
        <p className="description">
          Get started by editing <code className="code">app/page.tsx</code>
        </p>
      </main>
    </div>
  );
}
